export const ProductsData=[
    {
        "_id": "01JHAA5CC9A2HBK67PD9BM0N21",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "123455",
        "sale": false,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 5,
        "unitOfMeasure": "ml",
        "salePrice": 0,
        "availableItems": 7,
        "category": "Lotion",
        "units": "tagged",
        "price": 10,
        "comparison_weight": 1,
        "stock": {
            "total_value": 50,
            "average": 5,
            "last_restocked": 1736586947012,
            "value": 0,
            "total_stock": 0,
            "isStock": true,
            "minStock": 0
        },
        "title": "Tanning Lotion",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 0,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": true,
        "isBagActive": false,
        "sku": "4453",
        "deposit": 5,
        "teaser": "",
        "picture": "https://tanlux.s3.eu-north-1.amazonaws.com/ab25680f-916c-4b25-98cf-02cba5d2c8fa/images/ic_at_dawn.png",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": false,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "Tanning Lotion",
        "searchText": "tanning lotion#123455#4453",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:03.072Z",
        "updated": "2025-02-10T06:27:03.072Z"
    },
    {
        "_id": "01JJ14X3K87WTF0XKNFYQGEAB9",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "5654656",
        "sale": false,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 1,
        "unitOfMeasure": "ml",
        "salePrice": 2.94,
        "availableItems": 14,
        "category": "UNCATEGORY",
        "units": "tagged",
        "price": 3,
        "comparison_weight": 0,
        "stock": {
            "total_value": 56,
            "average": 1,
            "last_restocked": 1738157875939,
            "value": 29,
            "total_stock": 29,
            "isStock": true,
            "minStock": 0
        },
        "title": "Aqualogica sun screen",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 2,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": true,
        "isBagActive": true,
        "sku": "798989",
        "deposit": 25.8,
        "teaser": "",
        "picture": "",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": false,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "prakash",
        "searchText": "aqualogica sun screen#5654656#798989",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:02.985Z",
        "updated": "2025-02-10T06:27:02.985Z"
    },
    {
        "_id": "01JHAA6XD0RZTVAET6FREZ5J7H",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "9988893",
        "sale": true,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 5,
        "unitOfMeasure": "ml",
        "salePrice": 0,
        "availableItems": 9,
        "category": "Lotion",
        "units": "tagged",
        "price": 20,
        "comparison_weight": 1,
        "stock": {
            "total_value": 50,
            "average": 5,
            "last_restocked": 1736587283140,
            "value": 5,
            "total_stock": 1,
            "isStock": true,
            "minStock": 0
        },
        "title": "Bed Lotoin Two",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [
            {
                "count": 4,
                "price": 7,
                "status": "Active"
            },
            {
                "count": 6,
                "price": 9,
                "status": "Active"
            }
        ],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 0,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": false,
        "isBagActive": false,
        "sku": "212",
        "deposit": 1,
        "teaser": "",
        "picture": "https://tanlux.s3.eu-north-1.amazonaws.com/ab25680f-916c-4b25-98cf-02cba5d2c8fa/images/face-cream.png",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": false,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "",
        "searchText": "bed lotoin two#9988893#212",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:03.011Z",
        "updated": "2025-02-10T06:27:03.011Z"
    },
    {
        "_id": "01JJ153HGAXQWP7RGTS61TZBAX",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "8779",
        "sale": true,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 0,
        "unitOfMeasure": "ml",
        "salePrice": 0,
        "availableItems": 9,
        "category": "Lotion",
        "units": "tagged",
        "price": 1,
        "comparison_weight": 0,
        "stock": {
            "total_value": 0,
            "average": 0,
            "value": 0,
            "total_stock": 22,
            "isStock": true,
            "minStock": 0
        },
        "title": "De tan lotion",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [
            {
                "count": 1,
                "price": 3,
                "status": "Active"
            },
            {
                "count": 5,
                "price": 10,
                "status": "Active"
            },
            {
                "count": 8,
                "price": 15,
                "status": "Active"
            }
        ],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 0,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": false,
        "isBagActive": false,
        "sku": "76887",
        "deposit": 0,
        "teaser": "",
        "picture": "https://tanlux.s3.eu-north-1.amazonaws.com/ab25680f-916c-4b25-98cf-02cba5d2c8fa/images/face-cream.png",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": false,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "",
        "searchText": "de tan lotion#8779#76887",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:03.038Z",
        "updated": "2025-02-10T06:27:03.038Z"
    },
    {
        "_id": "01JJ1B0ZBVYZ0GM8WK197NB11X",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "7667676",
        "sale": false,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 0,
        "unitOfMeasure": "ml",
        "salePrice": 0,
        "availableItems": 9,
        "category": "Shower gel",
        "units": "tagged",
        "price": 2,
        "comparison_weight": 0,
        "stock": {
            "total_value": 0,
            "average": 0,
            "value": 0,
            "total_stock": 0,
            "isStock": true,
            "minStock": 0
        },
        "title": "De Tan gel",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 5,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": false,
        "isBagActive": false,
        "sku": "78798",
        "deposit": 0,
        "teaser": "",
        "picture": "",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": true,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "",
        "searchText": "de tan gel#7667676#78798",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:03.023Z",
        "updated": "2025-02-10T06:27:03.023Z"
    },
    {
        "_id": "01JJC1Z3D2CDJWWWKA5005NNEM",
        "shopId": "ab25680f-916c-4b25-98cf-02cba5d2c8fa",
        "stripeCode": "1231231231211",
        "sale": false,
        "importedAt": 0,
        "tax": 0,
        "purchasePrice": 5,
        "unitOfMeasure": "kg",
        "salePrice": 0,
        "availableItems": 10,
        "category": "Sun screen",
        "units": "tagged",
        "price": 30,
        "comparison_weight": 2,
        "stock": {
            "total_value": 150,
            "average": 5,
            "value": 115,
            "total_stock": 23,
            "isStock": true,
            "minStock": 0
        },
        "title": "sun screen 1",
        "wasted": 0,
        "soldItems": 0,
        "saleGroupRules": [],
        "updateVersion": 0,
        "ageRestriction": "",
        "quantity": 0,
        "isVending": true,
        "discount": 3,
        "priceDiff": 0,
        "originalPrice": 0,
        "noDepoPrice": 0,
        "promote": false,
        "isBagActive": false,
        "sku": "11212",
        "deposit": 5,
        "teaser": "",
        "picture": "",
        "isGS1": false,
        "expirationDate": "",
        "lastDeliveryDate": "",
        "isDiscount": true,
        "vendingDatas": [],
        "softDelete": false,
        "environment": "demo",
        "noneBarcode": false,
        "receiptName": "",
        "searchText": "sun screen 1#1231231231211#11212",
        "meta": {},
        "group": "general",
        "negative_stock": true,
        "isFridge": false,
        "productType": "vending",
        "created": "2025-02-10T06:27:03.069Z",
        "updated": "2025-02-10T06:27:03.069Z"
    }
  ]
  